#!/bin/bash

echo "🚀 Todo App Deployment Script"
echo "=============================="

echo ""
echo "📋 Prerequisites Checklist:"
echo "1. ✅ Node.js installed"
echo "2. ✅ Git repository initialized"
echo "3. ✅ MongoDB Atlas account created"
echo "4. ✅ Render account created"
echo "5. ✅ Vercel account created"

echo ""
echo "🔧 Step 1: MongoDB Atlas Setup"
echo "=============================="
echo "1. Go to https://www.mongodb.com/atlas"
echo "2. Create a free cluster"
echo "3. Create a database user"
echo "4. Get your connection string"
echo "5. Add IP whitelist (0.0.0.0/0 for all IPs)"

echo ""
echo "🔧 Step 2: Backend Deployment (Render)"
echo "======================================"
echo "1. Go to https://render.com"
echo "2. Create new Web Service"
echo "3. Connect your GitHub repo"
echo "4. Configure:"
echo "   - Name: todo-backend"
echo "   - Root Directory: backend"
echo "   - Environment: Node"
echo "   - Build Command: npm install"
echo "   - Start Command: npm start"
echo "5. Add Environment Variables:"
echo "   - MONGODB_URI: your-atlas-connection-string"
echo "   - NODE_ENV: production"

echo ""
echo "🔧 Step 3: Frontend Deployment (Vercel)"
echo "======================================="
echo "1. Go to https://vercel.com"
echo "2. Import your GitHub repo"
echo "3. Configure:"
echo "   - Framework: Create React App"
echo "   - Root Directory: frontend"
echo "4. Add Environment Variable:"
echo "   - REACT_APP_API_URL: https://your-backend-url.onrender.com/api"

echo ""
echo "🔧 Step 4: Update Configuration"
echo "==============================="
echo "After backend deployment, update frontend/src/config.js with your actual backend URL"

echo ""
echo "🧪 Step 5: Testing"
echo "=================="
echo "1. Visit your Vercel frontend URL"
echo "2. Test adding a task"
echo "3. Test completing a task"
echo "4. Test deleting a task"
echo "5. Refresh page to verify persistence"

echo ""
echo "✅ Deployment Complete!"
echo "======================"
echo "Frontend: https://your-app.vercel.app"
echo "Backend: https://your-app.onrender.com"
echo "Database: MongoDB Atlas" 